### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by roll** [conda-forge/datapackage-feedstock#9]
To resolve https://github.com/frictionlessdata/implementations/issues/34

```
    - cchardet >=1.0
    - click >=6.7
    - jsonpointer >=1.10
    - jsonschema >=2.5
    - requests >=2.8
    - six >=1.10
    - tableschema >=1.1.0
    - tabulator >=1.20
    - unicodecsv >=0.14
```

**Comment by ocefpaf** [comment]
Do you want to send a PR to fix that? All you want to do is to update the deps and bump the build number. Also, consider adding yourself as a maintainer so you can fix and merge this next time :wink:

**Comment by roll** [comment]
@ocefpaf 
Thanks. Done for both:
- https://github.com/conda-forge/tableschema-feedstock/pull/17
- https://github.com/conda-forge/datapackage-feedstock/pull/10
